# Site settings
title: "Hats and Co"
description: ""
baseurl: ""
url: "http://hatsandco.co.uk"
safe: true
exclude: ['README.md', 'LICENSE']

# Assets
css_url: /assets/css
js_url: /assets/js
sass:
    sass_dir: _scss
    style: :expanded

# Build settings
markdown: kramdown
permalink: pretty
